# Generated by Django 5.1.1 on 2024-10-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oppurtunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=None)),
                ('poster', models.ImageField(null=True, upload_to='')),
                ('short_desc', models.TextField(default=None)),
                ('domains', models.TextField(default=None)),
                ('description', models.TextField(default=None)),
                ('roles', models.TextField(default=None)),
                ('stipend', models.TextField(default=None)),
                ('duration', models.TextField(default=None)),
                ('tasks', models.TextField(default=None)),
                ('skills_gained', models.TextField(default=None)),
                ('req_quali', models.TextField(default=None)),
                ('gform', models.URLField(default=None)),
                ('deadline', models.TextField(default=None)),
                ('contact_info', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField(default=None)),
                ('poster', models.ImageField(default=None, upload_to='')),
                ('short_desc', models.TextField(default=None)),
                ('program', models.TextField(default=None, null=True)),
                ('club', models.TextField(default=None)),
                ('markdown', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collab', models.BooleanField(default=False)),
                ('projects_collab', models.TextField(default=None, null=True)),
                ('name', models.TextField(default=None)),
                ('yr_of_study', models.CharField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], default='1st', max_length=3)),
            ],
        ),
    ]
